language: node_js
node_js:
  - "stable"
script:
  - npm install
  - cd react-frontend
  - npm run build --loglevel verbose
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master